extern void aes128_enckey(const void *in, void *out);
extern void aes128_deckey(const void *in, void *out);
extern void aes192_enckey(const void *in, void *out);
extern void aes192_deckey(const void *in, void *out);
extern void aes256_enckey(const void *in, void *out);
extern void aes256_deckey(const void *in, void *out);
extern void aes128_encrypt(const void *key, const void *in, void *out);
extern void aes128_decrypt(const void *key, const void *in, void *out);
extern void aes192_encrypt(const void *key, const void *in, void *out);
extern void aes192_decrypt(const void *key, const void *in, void *out);
extern void aes256_encrypt(const void *key, const void *in, void *out);
extern void aes256_decrypt(const void *key, const void *in, void *out);
extern void aes_ecb_encrypt(void(*fn)(const void *, const void *, void *), const void *key, unsigned size, const void *in, void *out);
extern void aes_ecb_decrypt(void(*fn)(const void *, const void *, void *), const void *key, unsigned size, const void *in, void *out);
extern void aes_cbc_encrypt(void(*fn)(const void *, const void *, void *), const void *key, const void *iv, unsigned size, const void *in, void *out);
extern void aes_cbc_decrypt(void(*fn)(const void *, const void *, void *), const void *key, const void *iv, unsigned size, const void *in, void *out);
extern void aes_cfb_encrypt(void(*fn)(const void *, const void *, void *), const void *key, const void *iv, unsigned size, const void *in, void *out);
extern void aes_cfb_decrypt(void(*fn)(const void *, const void *, void *), const void *key, const void *iv, unsigned size, const void *in, void *out);
extern void aes_ofb_encrypt(void(*fn)(const void *, const void *, void *), const void *key, const void *iv, unsigned size, const void *in, void *out);
extern void aes_ofb_decrypt(void(*fn)(const void *, const void *, void *), const void *key, const void *iv, unsigned size, const void *in, void *out);