// This file was auto-generated by ML.NET Model Builder. 

using System;
using Instagram_archiverML.Model;

namespace Instagram_archiverML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                ImageSource = @"C:\Users\mnjihw\Documents\Visual Studio 2019\Projects\instagram_archiver\instagram_archiver\images\etc\0985ED1AE3C3465A4C4297CBF13F3F0E8A848BCD6EDCD0D022B41D29B0FB8A94.jpg",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");
            Console.WriteLine($"ImageSource: {sampleData.ImageSource}");
            Console.WriteLine($"\n\nPredicted Label value {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
