using System.Windows.Forms;

namespace 리듬_DC_맞춤법_봇
{
    public class Point_out
    {
        public const string e1 = "(되어 = 돼임)";
        public const string e2 = "(받침 있으면 이에요 없으면 예요 이로 끝나면 받침 없으므로 예요 요 떼서 말 되면 에요 아니에요는 예외 인명엔 예요(예 : 길동이예요) 성까지 쓰면 이에요(예 : 홍길동이에요))";
        public const string e3 = "(국어사전 - 엔간하다 [형용사] : 대중으로 보아 정도가 표준에 꽤 가깝다.)";
        public const string e4 = "(왠지 빼고 웬임)";
        public const string e5 = "(무조건 며칠이 맞음)";
        public const string e6 = "(국어사전 - 함부로 [부사] : 조심하거나 깊이 생각하지 아니하고 마음 내키는 대로 마구.)";
        public const string e7 = "(국어사전 - 금세 [부사] : 지금 바로.금시에가 줄어든 말로 구어체에서 많이 사용된다.)";
        public const string e8 = "(국어사전 - 요새 [명사] :‘요사이(이제까지의 매우 짧은 동안)’의 준말.)";
        public const string e9 = "(뵈어 = 봬임)";
        public const string e10 = "(틈틈이 간간이 누누이 곰곰이 일일이 짬짬이 번번이 깨끗이 깊숙이 등등...)";
        public const string e11 = "(기본형이 붙히다가 아니고 붙이다임)";
        public const string e12 = "(아니었 아니에요 아니어도 아니어서는 예외)";
        public const string e13 = "(국어사전 - 얻다 : ‘어디에다’가 줄어든 말.)";
        public const string e14 = "(국어사전 - 오랜만 [명사] :오래간만(어떤 일이 있은 때로부터 긴 시간이 지난 뒤)의 준말.)";
        public const string e15 = "(역할 (役割)[명사] :  자기가 마땅히 하여야 할 맡은 바 직책이나 임무.)";
        public const string e16 = "(굳이가 구개음화돼서 구지로 발음됨)";
        public const string e17 = "(어떻게 해 = 어떡해임)";
        public const string e18 = "(-ㄹ는지 : 막연한 의문이나 의심을 나타낼 때 사용하는 어미)";
        public const string e19 = "(개수 (個數)[명사] : 한 개씩 낱으로 셀 수 있는 물건의 수효.)";
        public const string e20 = "(녹록지 넉넉지 익숙지 섭섭지 등등...)";
        public const string e21 = "(계시다는 동사라 형용사 뒤에 쓰이는 어미 -ㄴ가(요)를 붙인 계신가요는 적절하지 않고, 주로 동사 뒤에 쓰이는 어미 -나(요)를 붙인 계시나요가 적절함)";
        public const string e22 = "(국어사전 - 지껄이다 [동사] : 1. 약간 큰 소리로 떠들썩하게 이야기하다. 2. ‘말하다’를 낮잡아 이르는 말.)";
        public const string e23 = "(국어사전 - 짜깁기 [명사] : 기존의 글이나 영화 따위를 편집하여 하나의 완성품으로 만드는 일.)";
        public const string e24 = "(국어사전 - 곁땀 [명사] : 겨드랑이에서 나는 땀.)";
        public const string e25 = "(국어사전 - 들입다 [부사] : 세차게 마구.)";
        public const string e26 = "(국어사전 - 해님 [명사] : 해를 인격화하여 높이거나 다정하게 이르는 말.)";
        public const string e27 = "(국어사전 - 고데기 : 미용실에서 웨이브를 연출할 때 사용하는 둥근 형태로 된 기계.)";
        public const string e28 = "(국어사전 - 헤매다 [동사] : 갈 바를 몰라 이리저리 돌아다니다.)";
        public const string e29 = "(국어사전 - 돌멩이 [명사] : 돌덩이보다 작은 돌.)";
        public const string e30 = "(국어사전 - 알맹이 [명사] : 1. 물건의 껍데기나 껍질을 벗기고 남은 속 부분.  2. 사물의 핵심이 되는 중요한 부분.)";
        public const string e31 = "(국어사전 - 눈곱 [명사] : 눈에서 나오는 진득진득한 액.또는 그것이 말라붙은 것.)";
        public const string e32 = "(국어사전 - 설거지 [명사] : 먹고 난 뒤의 그릇을 씻어 정리하는 일.)";
        public const string e33 = "(국어사전 - 희한하다 [형용사] : 매우 드물거나 신기하다.)";
        public const string e34 = "(국어사전 - 도긴개긴 [명사] : 조금 낫고 못한 정도의 차이는 있으나 본질적으로는 비슷비슷하여 견주어 볼 필요가 없음을 이르는 말.)";
        public const string e35 = "(국어사전 - 십상 (十常)[명사] : 같은 말 : 십상팔구(열에 여덟이나 아홉 정도로 거의 예외가 없음.))";
        public const string e36 = "(이중 피동)";
        public const string e37 = "(영어사전 - tutorial : 1. (대학의)개별 지도 시간   2. 사용 지침서, (컴퓨터의)사용 지침 프로그램)";
        public const string e38 = "(국어사전 - 순댓국 [명사] : 돼지를 삶은 국물에 순대를 넣고 끓인 국.)";
        public const string e39 = "(국어사전 - 만둣국 [명사] : 만두를 넣고 끓인 국.)";
        public const string e40 = "(국어사전 - 대가 (代價) [명사] : 1. 같은 말 : 대금5(代金)(물건의 값으로 치르는 돈). 2. 일을 하고 그에 대한 값으로 받는 보수.)";
        public const string e41 = "(국어사전 - 이점 (利點) [명사] : 이로운 점.)";
        public const string e42 = "(국어사전 - 나잇값 [명사] : 나이에 어울리는 말과 행동을 낮잡아 이르는 말.)";
        public const string e43 = "(국어사전 - 죗값 [명사] : 지은 죄에 대하여 치르는 대가.)";
        public const string e44 = "(국어사전 - 공깃밥 [명사] : 공기에 담은 밥.)";
        public const string e45 = "(받침 있으면 률 없거나 ㄴ받침이면 율)";
        public const string e46 = "(상호가 배스킨라빈스 31임)";
        public const string e47 = "(국어사전 - 카디건 (cardigan)[명사] : 털로 짠 스웨터의 하나.)";
        public const string e48 = "(국어사전 - 훼손 (毁損)[명사] : 1. 체면이나 명예를 손상함. 2. 헐거나 깨뜨려 못 쓰게 만듦.)";
        public const string e49 = "(국어사전 - 폐쇄 (閉鎖)[명사] : 1. 문 따위를 닫아걸거나 막아 버림. 2. 기관이나 시설을 없애거나 기능을 정지함.)";
        public const string e50 = "(국어사전 - 급처 : 게임에서 아이템을 팔 때 쓰는 말. 급하게 처분의 줄임말.)";
        public const string e51 = "(국어사전 - 얼마큼 :얼마만큼이 줄어든 말.)";
        public const string e52 = "(국어사전 - 대갚음 [명사] : 남에게 입은 은혜나 남에게 당한 원한을 잊지 않고 그대로 갚음.)";
        public const string e53 = "(국어사전 - 구레나룻 [명사] : 귀밑에서 턱까지 잇따라 난 수염.)";
        public const string e54 = "(국어사전 - 저녁 [명사] : 해가 질 무렵부터 밤이 되기까지의 사이.)";
        public const string e55 = "(국어사전 - 반대말 [명사] : 같은 말 : 반의어(그 뜻이 서로 정반대되는 관계에 있는 말).)";
        public const string e56 = "(국어사전 - 파투 [명사] : 일이 잘못되어 흐지부지됨을 비유적으로 이르는 말.)";
        public const string e57 = "(국어사전 - 어쭙잖다 [형용사] : 비웃음을 살 만큼 언행이 분수에 넘치는 데가 있다.)";
        public const string e58 = "(국어사전 - 뒤치다꺼리 [명사] :  뒤에서 일을 보살펴서 도와주는 일.)";
        public const string e59 = "(국어사전 - 씨불이다 [동사] : 주책없이 함부로 실없는 말을 하다.)";
        public const string e60 = "(국어사전 - 지르밟다 [동사] : 위에서 내리눌러 밟다.)";
        public const string e61 = "(국어사전 - 아등바등 [부사] : 무엇을 이루려고 애를 쓰거나 우겨 대는 모양.)";
        public const string e62 = "(국어사전 - 장롱 [명사] : 옷 따위를 넣어 두는 장과 농을 아울러 이르는 말.)";
        public const string e63 = "(국어사전 - 철석같이 [부사] : 마음이나 의지, 약속 따위가 매우 굳고 단단하게.)";
        public const string e64 = "(국어사전 - 어리바리 [부사] : 정신이 또렷하지 못하거나 기운이 없어 몸을 제대로 놀리지 못하고 있는 모양.)";
        public const string e65 = "(국어사전 - 매가리 [명사] : 맥(기운이나 힘)(脈)을 낮잡아 이르는 말.)";
        public const string e66 = "(빨강은 빨간 빛깔이라는 뜻으로 그 뒤에 색을 붙일 필요가 없음)";
        public const string e67 = "(외래어는 뒤 초성이 거센소리나 된소리일 때 앞 받침을 안 적는 게 원칙. 쉽게 말하자면 받침 유무에 따라 발음 차이가 없으면 받침 안 씀)";
        public const string e68 = "(navi[|nӕvɪ] 이므로 내비가 맞음)";
        public const string e69 = "(외래어표기법 제 3장 제 6항 유음([l]) - 어중의 [l]이 모음 앞에 오면 ㄹㄹ로 적는다. 한국 롤렉스 홈피에도 롤렉스로 표기함.)";
        public const string e70 = "(DAYJUST가 아닌 DATEJUST임)";
        public const string e71 = "(국어사전 - 도대체 (都大體)[부사] : 1. 다른 말은 그만두고 요점만 말하자면. 2. 유감스럽게도 전혀.)";
        public const string e72 = "(영어사전 - 오토매틱 [예문] : 오토매틱의 automatic)";
        public const string e73 = "(국어사전 - 별의별 (別-別)[관형사] : 보통과 다른 갖가지의.)";
        public const string e74 = "(담구다가 아니고 담그다임)";
        public const string e75 = "(Tangente[taŋ|gεntә]로 탕겐테가 맞음)";
        public const string e76 = "(platinum이므로 플래티넘이 맞음. 늄은 nium으로 쓸 경우임)";
        public const string e77 = "(국어사전 - 재작년 (再昨年)[명사] : 지난해의 바로 전 해.)";
        public const string e78 = "(국어사전 - 불리다 [동사] : 부르다(말이나 행동 따위로 다른 사람의 주의를 끌거나 오라고 하다.)의 피동사.)";
        public const string e79 = "(국어사전 - 모자라다 [동사] : 기준이 되는 양이나 정도에 미치지 못하다.)";
        public const string e80 = "(국어사전 - 건드리다 [동사] : 조금 움직일 만큼 손으로 만지거나 무엇으로 대다.)";
        public const string e81 = "(그렇다가 형용사라 그런가요가 맞음)";
        public const string e82 = "(국어사전 - 짚이다 [동사] : 헤아려 본 결과 어떠할 것으로 짐작이 가다.)";
        public const string e83 = "(국어사전 - 높이다 [동사] : 높다의 사동사.)";
        public const string e84 = "(국어사전 - 삼가다 [동사] : 1. 몸가짐이나 언행을 조심하다. 2.꺼리는 마음으로 양(量)이나 횟수가 지나치지 아니하도록 하다.)";
        public const string e85 = "(국어사전 - 횡격막 (橫膈膜/橫隔膜)[명사] : [같은 말] 가로막(배와 가슴 사이를 분리하는 근육).)";
        public const string e86 = "(예컨대 단언컨대 생각건대 하건대 등등..)";
        public const string e87 = "(국어사전 - 맡기다 [동사] : 맡다(어떤 일에 대한 책임을 지고 담당하다)의 사동사.)";
        public const string e88 = "(국어사전 - 유도신문 (誘導訊問) : 증인을 신문하는 사람이 희망하는 답변을 암시하면서, 증인이 무의식중에 원하는 대답을 하도록 꾀어 묻는 일.)";
        public const string e89 = "(뒤 초성이 된소리나 거센소리일 때는 사이시옷을 안 적는 게 원칙임)";
        public const string e90 = "(국어사전 - 홍채 [명사] : 안구의 각막과 수정체 사이에 있는 둥근 모양의 얇은 막.)";
        public const string e91 = "(이요는 연결 어미라 쉼표 앞이나 요 떼서 말 될 때만 올 수 있고 요는 해요체 이오는 하오체라 일상에서 쓸 때는 이오보단 요가 적절함)";
        public const string e92 = "(받침 있으면 이었 없으면 였 이로 끝나면 받침 없으므로 였 아니었은 예외 인명엔 였(예 : 길동이였다) 성까지 쓰면 이었다(예 : 홍길동이었다))";
        public const string e93 = "(받침 있으면 이어도 없으면 여도 이로 끝나면 받침 없으므로 여도 아니어도는 예외 인명엔 여도(예 : 길동이여도) 성까지 쓰면 이어도(예 : 홍길동이어도))";
        public const string e94 = "(받침 있으면 이어서 없으면 여서 이로 끝나면 받침 없으므로 여서 아니어서는 예외 인명엔 여서(예 : 길동이여서) 성까지 쓰면 이어서(예 : 홍길동이어서))";
        public const string e95 = "(선택은 든 과거 회상은 던)";
        public const string e96 = "(국어사전 - 바라다[동사] : 1. 생각이나 바람대로 어떤 일이나 상태가 이루어지거나 그렇게 되었으면 하고 생각하다.)";
        public const string e97 = "(지위, 신분, 자격은 로서(예 : 친구로서 등) 재료, 수단, 도구, 시간을 셀 때 셈에 넣는 한계는 로써(예 : 흙으로써, 함으로써, 오늘로써 등))";
        public const string e98 = "(국어사전 - 애먼 [관형사] : 1. 일의 결과가 다른 데로 돌아가 억울하게 느껴지는. 2. 일의 결과가 다른 데로 돌아가 엉뚱하게 느껴지는.)";
        public const string e99 = "(응 아니의 높임 표현은 예 아니요임. 아니오는 그는 사람이 아니오. 와 같이 씀)";
        public const string e100 = "(국어사전 - -다시피 :  1.‘-는 바와 같이’의 뜻을 나타내는 연결 어미. 2. 어떤 동작에 가까움을 나타내는 연결 어미.)";
        public const string e101 = "(걸맞다는 형용사라 동사 뒤에 쓰이는 어미 -는를 붙인 걸맞는은 적절하지 않고, 주로 형용사 뒤에 쓰이는 어미 -은을 붙인 걸맞은이 적절함)";
        public const string e102 = "(국어사전 - 태엽 (胎葉) [명사] 얇고 긴 강철 띠를 돌돌 말아 그 풀리는 힘으로 시계 따위를 움직이게 하는 장치.)";
        public const string e103 = "(sh는 시로 표기함. 스킨십 멤버십 플래그십 플래시 등등...)";
        public const string e104 = "(국어사전 - 플래카드 (placard)[명사] 긴 천에 표어 따위를 적어 양쪽을 장대에 매어 높이 들거나 길 위에 달아 놓은 표지물.)";
        public const string e105 = "(국어사전 - 난센스 (nonsense)[명사] 이치에 맞지 아니하거나 평범하지 아니한 말 또는 일.)";
        public const string e106 = "(발음기호가 [ʃӕ]이면 섀 [ʃe]이면 셰. 쉐는 아예 틀림)";
        public const string e107 = "(swag[swӕg]이므로 스왜그가 맞고 굳이 줄이자면 스왝이 맞음)";
        public const string e108 = "(swagger[|swӕgə(r)]이므로 스왜거가 맞음)";


        private static int ps_idx, ps2_idx;

        public struct pointed_out_t
        {
            public int idx;
            public string nick;
        }

        public static int get_ps_idx() =>  ps_idx;

        public static int get_ps2_idx() => ps2_idx;

        static void ps_setup(string s1, string s2, string s3)
        {
            if (ps_idx >= Form1.PS_MAX)
            {
                MessageBox.Show("PS_MAX 초과함!");
                return;
            }
            Form1.ps[ps_idx].wrongstring = s1;
            Form1.ps[ps_idx].correctstring = s2;
            Form1.ps[ps_idx].explanation = s3;
            ++ps_idx;
        }

        static void ps2_setup(string s1, string s2, string s3)
        {
            if(ps2_idx >= Form1.PS2_MAX)
            {
                MessageBox.Show("PS2_MAX 초과함!");
                return;
            }
            Form1.ps2[ps2_idx].wrongstring = s1;
            Form1.ps2[ps2_idx].correctstring = s2;
            Form1.ps2[ps2_idx].explanation = s3;
            ++ps2_idx;
        }

        public static void ps_init()
        {
            ps_setup("되", "돼", e1);
            ps_setup("되요", "돼요", e1);
            ps_setup("되여", "돼여", e1);
            ps_setup("되욤", "돼욤", e1);
            ps_setup("되염", "돼염", e1);
            ps_setup("되용", "돼용", e1);
            ps_setup("되영", "돼영", e1);
            ps_setup("되욧", "돼욧", e1);
            ps_setup("되엿", "돼엿", e1);
            ps_setup("되양", "돼양", e1);
            ps_setup("되얌", "돼얌", e1);
            ps_setup("되야", "돼야", e1);
            ps_setup("되서", "돼서", e1);
            ps_setup("되봐", "돼봐", e1);
            ps_setup("됫", "됐", e1);
            ps_setup("됬", "됐", e1);
            ps_setup("되가", "돼가", e1);
            ps_setup("되간다", "돼간다", e1);
            ps_setup("되갈", "돼갈", e1);
            ps_setup("되와", "돼와", e1);
            ps_setup("되왔", "돼왔", e1);
            ps_setup("되온다", "돼온다", e1);
            ps_setup("되잇", "돼있", e1);
            ps_setup("되있", "돼있", e1);
            ps_setup("되 있", "돼 있", e1);
            ps_setup("되버림", "돼버림", e1);
            ps_setup("되버린", "돼버린", e1);
            ps_setup("되버렷", "돼버렸", e1);
            ps_setup("되버렸", "돼버렸", e1);
            ps_setup("되버리는", "돼버리는", e1);
            ps_setup("되버리고", "돼버리고", e1);
            ps_setup("되버리지", "돼버리지", e1);
            ps_setup("되버려", "돼버려", e1);
            ps_setup("되보임", "돼보임", e1);
            ps_setup("되보여", "돼보여", e1);
            ps_setup("되보인다", "돼보인다", e1);
            ps_setup("되보여서", "돼보여서", e1);
            ps_setup("되보엿", "돼보였", e1);
            ps_setup("되보였", "돼보였", e1);
            ps_setup("되보이", "돼보이", e1);
            ps_setup("되보일", "돼보일", e1);
            ps_setup("되보여야", "돼보여야", e1);
            ps_setup("됌", "됨", e1);
            ps_setup("되도", "돼도", e1);
            ps_setup("되라", "돼라", e1);
            ps_setup("돼는데", "되는데", e1);
            ps_setup("뭐에요", "뭐예요", e2);
            ps_setup("뭐에여", "뭐예여", e2);
            ps_setup("뭐에염", "뭐예염", e2);
            ps_setup("뭐에야", "뭐예야", e2);
            ps_setup("뭐에얌", "뭐예얌", e2);
            ps_setup("뭐에욧", "뭐예욧", e2);
            ps_setup("뭐에엿", "뭐예엿", e2);
            ps_setup("머에요", "머예요", e2);
            ps_setup("머에여", "머예여", e2);
            ps_setup("머에염", "머예염", e2);
            ps_setup("머에야", "머예야", e2);
            ps_setup("머에얌", "머예얌", e2);
            ps_setup("머에욧", "머예욧", e2);
            ps_setup("머에엿", "머예엿", e2);
            ps_setup("거에요", "거예요", e2);
            ps_setup("거에여", "거예여", e2);
            ps_setup("거에염", "거예염", e2);
            ps_setup("거에야", "거예야", e2);
            ps_setup("거에얌", "거예얌", e2);
            ps_setup("거에욧", "거예욧", e2);
            ps_setup("거에엿", "거예엿", e2);
            ps_setup("거에욬", "거예욬", e2);
            ps_setup("거에옄", "거예옄", e2);
            ps_setup("꺼에요", "꺼예요", e2); 
            ps_setup("꺼에여", "꺼예여", e2);
            ps_setup("꺼에염", "꺼예염", e2);
            ps_setup("꺼에야", "꺼예야", e2);
            ps_setup("꺼에얌", "꺼예얌", e2);
            ps_setup("꺼에욧", "꺼예욧", e2);
            ps_setup("꺼에엿", "꺼예엿", e2);
            ps_setup("꺼에욬", "꺼예욬", e2);
            ps_setup("꺼에옄", "꺼예옄", e2);
            ps_setup("앵간", "엔간", e3);
            ps_setup("왠만", "웬만", e4);
            ps_setup("왠일", "웬일", e4);
            ps_setup("왠", "웬", e4);
            ps_setup("웬지", "왠지", e4);
            ps_setup("몇일", "며칠", e5);
            ps_setup("함부러", "함부로", e6);
            ps_setup("금새", "금세", e7);
            ps_setup("요세", "요새", e8);
            ps_setup("뵈요", "봬요", e9);
            ps_setup("뵈여", "봬여", e9);
            ps_setup("뵈염", "봬염", e9);
            ps_setup("뵜", "뵀", e9);
            ps_setup("뵈서", "봬서", e9);
            ps_setup("틈틈히", "틈틈이", e10);
            ps_setup("간간히", "간간이", e10);
            ps_setup("누누히", "누누이", e10);
            ps_setup("곰곰히", "곰곰이", e10);
            ps_setup("일일히", "일일이", e10);
            ps_setup("짬짬히", "짬짬이", e10);
            ps_setup("번번히", "번번이", e10);
            ps_setup("깨끗히", "깨끗이", e10);
            ps_setup("깊숙히", "깊숙이", e10);
            ps_setup("붙혔", "붙였", e11);
            ps_setup("붙혀", "붙여", e11);
            ps_setup("붙히는", "붙이는", e11);
            ps_setup("붙힐", "붙일", e11);
            ps_setup("아니엿", "아니었", e12);
            ps_setup("아니였", "아니었", e12);
            ps_setup("아니예요", "아니에요", e12);
            ps_setup("아니여도", "아니어도", e12);
            ps_setup("어따", "얻다", e13);
            ps_setup("오랫만", "오랜만", e14);
            ps_setup("역활", "역할", e15);
            ps_setup("궂이", "굳이", e16);
            ps_setup("궃이", "굳이", e16);
            ps_setup("어떻함", "어떡함", e17);
            ps_setup("어떻해", "어떡해", e17);
            ps_setup("할런지", "할는지", e18);
            ps_setup("될런지", "될는지", e18);
            ps_setup("을런지", "을는지", e18);
            ps_setup("보일런지", "보일는지", e18);
            ps_setup("아닐런지", "아닐는지", e18);
            ps_setup("갯수", "개수", e19);
            ps_setup("이래뵈도", "이래봬도", e9);
            ps_setup("녹록치", "녹록지", e20);
            ps_setup("넉넉치", "넉넉지", e20);
            ps_setup("익숙치", "익숙지", e20);
            ps_setup("섭섭치", "섭섭지", e20);
            ps_setup("계신가요", "계시나요", e21);
            ps_setup("계신가여", "계시나여", e21);
            ps_setup("계신가욤", "계시나욤", e21);
            ps_setup("계신가염", "계시나염", e21);
            ps_setup("계신가용", "계시나용", e21);
            ps_setup("계신가영", "계시나영", e21);
            ps_setup("계시다면", "계신다면", e21);
            ps_setup("짓걸이네", "지껄이네", e22);
            ps_setup("짓거리네", "지껄이네", e22);
            ps_setup("짓껄이네", "지껄이네", e22);
            ps_setup("짓꺼리네", "지껄이네", e22);
            ps_setup("짓걸이지", "지껄이지", e22);
            ps_setup("짓거리지", "지껄이지", e22);
            ps_setup("짓껄이지", "지껄이지", e22);
            ps_setup("짓꺼리지", "지껄이지", e22);
            ps_setup("짓걸임", "지껄임", e22);
            ps_setup("짓거림", "지껄임", e22);
            ps_setup("짓껄임", "지껄임", e22);
            ps_setup("짓꺼림", "지껄임", e22);
            ps_setup("짜집기", "짜깁기", e23);
            ps_setup("겨땀", "곁땀", e24);
            ps_setup("드립다", "들입다", e25);
            ps_setup("햇님", "해님", e26);
            ps_setup("고대기", "고데기", e27);
            ps_setup("헤메다", "헤매다", e28);
            ps_setup("헤멤", "헤맴", e28);
            ps_setup("헤메도", "헤매도", e28);
            ps_setup("헤멨", "헤맸", e28);
            ps_setup("돌맹이", "돌멩이", e29);
            ps_setup("알멩이", "알맹이", e30);
            ps_setup("눈꼽", "눈곱", e31);
            ps_setup("설겆이", "설거지", e32);
            ps_setup("희안", "희한", e33);
            ps_setup("도찐개찐", "도긴개긴", e34);
            ps_setup("쉽상", "십상", e35);
            ps_setup("보여짐", "보임", e36);
            ps_setup("보여집", "보입", e36);
            ps_setup("보여질", "보일", e36);
            ps_setup("보여져", "보여", e36);
            ps_setup("보여졌", "보였", e36);
            ps_setup("보여진", "보인", e36);
            ps_setup("보여지지", "보이지", e36);
            ps_setup("보여지질", "보이질", e36);
            ps_setup("보여지는", "보이는", e36);
            ps_setup("보여지네", "보이네", e36);
            ps_setup("보여지고", "보이고", e36);
            ps_setup("잊혀집", "잊힙", e36);
            ps_setup("잊혀짐", "잊힘", e36);
            ps_setup("잊혀지지", "잊히지", e36);
            ps_setup("잊혀지질", "잊히질", e36);
            ps_setup("잊혀질", "잊힐", e36);
            ps_setup("잊혀져", "잊혀", e36);
            ps_setup("잊혀지는", "잊히는", e36);
            ps_setup("잊혀졌", "잊혔", e36);
            ps_setup("잊혀진", "잊힌", e36);
            ps_setup("믿겨집", "믿깁", e36);
            ps_setup("믿겨짐", "믿김", e36);
            ps_setup("믿겨질", "믿길", e36);
            ps_setup("믿겨져", "믿겨", e36);
            ps_setup("믿겨졌", "믿겼", e36);
            ps_setup("믿겨진", "믿긴", e36);
            ps_setup("믿겨지지", "믿기지", e36);
            ps_setup("믿겨지질", "믿기질", e36);
            ps_setup("믿겨지는", "믿기는", e36);
            ps_setup("믿겨지네", "믿기네", e36);
            ps_setup("짜여집", "짜입", e36);
            ps_setup("짜여짐", "짜임", e36);
            ps_setup("짜여지지", "짜이지", e36);
            ps_setup("짜여지질", "짜이질", e36);
            ps_setup("짜여질", "짜일", e36);
            ps_setup("짜여져", "짜여", e36);
            ps_setup("짜여지는", "짜이는", e36);
            ps_setup("짜여졌", "짜였", e36);
            ps_setup("짜여진", "짜인", e36);
            ps_setup("쓰여집", "쓰입", e36);
            ps_setup("쓰여짐", "쓰임", e36);
            ps_setup("쓰여질", "쓰일", e36);
            ps_setup("쓰여져", "쓰여", e36);
            ps_setup("쓰여졌", "쓰였", e36);
            ps_setup("쓰여진", "쓰인", e36);
            ps_setup("쓰여지지", "쓰이지", e36);
            ps_setup("쓰여지질", "쓰이질", e36);
            ps_setup("쓰여지는", "쓰이는", e36);
            ps_setup("쓰여지네", "쓰이네", e36);
            ps_setup("듀토리얼", "튜토리얼", e37);
            ps_setup("순대국", "순댓국", e38);
            ps_setup("만두국", "만둣국", e39);
            ps_setup("댓가", "대가", e40);
            ps_setup("잇점", "이점", e41);
            ps_setup("나이값", "나잇값", e42);
            ps_setup("담배값", "담뱃값", "");
            ps_setup("죄값", "죗값", e43);
            ps_setup("공기밥", "공깃밥", e44);
            ps_setup("임신률", "임신율", e45);
            ps_setup("할인률", "할인율", e45);
            ps_setup("베스킨", "배스킨", e46);
            ps_setup("가디건", "카디건", e47);
            ps_setup("회손", "훼손", e48);
            ps_setup("폐쇠", "폐쇄", e49);
            ps_setup("급쳐", "급처", e50);
            ps_setup("얼만큼", "얼마큼", e51);
            ps_setup("되갚음", "대갚음", e52);
            ps_setup("구렛나루", "구레나룻", e53);
            ps_setup("저녘", "저녁", e54);
            ps_setup("반댓말", "반대말", e55);
            ps_setup("파토", "파투", e56);           
            ps_setup("어줍잖", "어쭙잖", e57);
            ps_setup("뒤치닥거리", "뒤치다꺼리", e58);
            ps_setup("씨부림", "씨불임", e59);
            ps_setup("시부림", "씨불임", e59);
            ps_setup("씨부리지", "씨불이지", e59);
            ps_setup("시부리지", "씨불이지", e59);
            ps_setup("씨부리질", "씨불이질", e59);
            ps_setup("시부리질", "씨불이질", e59);
            ps_setup("씨부릴", "씨불일", e59);
            ps_setup("시부릴", "씨불일", e59);
            ps_setup("씨부려", "씨불여", e59);
            ps_setup("시부려", "씨불여", e59);
            ps_setup("씨부리는", "씨불이는", e59);
            ps_setup("시부리는", "씨불이는", e59);
            ps_setup("씨부렷", "씨불였", e59);
            ps_setup("시부렷", "씨불였", e59);
            ps_setup("씨부렸", "씨불였", e59);
            ps_setup("시부렸", "씨불였", e59);
            ps_setup("씨부린", "씨불인", e59);
            ps_setup("씨부리면", "씨불이면", e59);
            ps_setup("시부리면", "씨불이면", e59);
            ps_setup("즈려밟", "지르밟", e60);
            ps_setup("아둥바둥", "아등바등", e61);
            ps_setup("장농", "장롱", e62);
            ps_setup("철썩같이", "철석같이", e63);
            ps_setup("어리버리", "어리바리", e64);
            ps_setup("맥아리", "매가리", e65);
            ps_setup("빨강색", "빨간색(빨강)", e66);
            ps_setup("셋트", "세트", e67);
            ps_setup("셋팅", "세팅", e67);
            ps_setup("티켓팅", "티케팅", e67);
            ps_setup("랩퍼", "래퍼", e67);
            ps_setup("랩핑", "래핑", e67);
            ps_setup("마켓팅", "마케팅", e67);
            ps_setup("컷팅", "커팅", e67);
            ps_setup("컷터", "커터", e67);
            ps_setup("네비", "내비", e68);
            ps_setup("로렉스", "롤렉스", e69);
            ps_setup("데이저스트", "데이트저스트(데잇저스트)", e70);
            ps_setup("데이져스트", "데이트저스트(데잇저스트)", e70);
            ps_setup("도데체", "도대체", e71);
            ps_setup("오토메틱", "오토매틱", e72);
            ps_setup("별에별", "별의별", e73);
            ps_setup("담궈", "담가", e74);
            ps_setup("탕켄테", "탕겐테", e75);
            ps_setup("플래티늄", "플래티넘", e76);
            ps_setup("플레티늄", "플래티넘", e76);
            ps_setup("플레티넘", "플래티넘", e76);
            ps_setup("제작년", "재작년", e77);
            ps_setup("불리움", "불림", e78);
            ps_setup("불리우는", "불리는", e78);
            ps_setup("불리운", "불린", e78);
            ps_setup("불리우게", "불리게", e78);
            ps_setup("불리어", "불려", e78);
            ps_setup("모자름", "모자람", e79);
            ps_setup("모자른", "모자란", e79);
            ps_setup("건들여", "건드려", e80);
            ps_setup("건들임", "건드림", e80);
            ps_setup("건들이는", "건드리는", e80);
            ps_setup("건들이지", "건드리지", e80);
            ps_setup("그렇나요", "그런가요", e81);
            ps_setup("짚히는", "짚이는", e82);
            ps_setup("짚힘", "짚임", e82);
            ps_setup("짚혀", "짚여", e82);
            ps_setup("짚혔", "짚였", e82);
            ps_setup("높혀", "높여", e83);
            ps_setup("높히", "높이", e83);
            ps_setup("높혔", "높였", e83);
            ps_setup("높힌", "높인", e83);
            ps_setup("삼가해", "삼가", e84);
            ps_setup("삼가하세요", "삼가세요", e84);
            ps_setup("삼가하셈", "삼가셈", e84);
            ps_setup("횡경막", "횡격막", e85);
            ps_setup("예컨데", "예컨대", e86);
            ps_setup("단언컨데", "단언컨대", e86);
            ps_setup("생각컨데", "생각건대", e86);
            ps_setup("생각컨대", "생각건대", e86);
            ps_setup("하건데", "하건대", e86);
            ps_setup("맞기다", "맡기다", e87);
            ps_setup("맞김", "맡김", e87);
            ps_setup("맞기지", "맡기지", e87);
            ps_setup("맞겨", "맡겨", e87);
            ps_setup("맞겼", "맡겼", e87);
            ps_setup("유도심문", "유도신문", e88);
            ps_setup("뒷", "뒤", e89);
            ps_setup("윗", "위", e89);
            ps_setup("아랫", "아래", e89);
            ps_setup("홍체", "홍채", e90);
            ps_setup("싶이", "시피", e100);
            ps_setup("걸맞는", "걸맞은", e101);
            ps_setup("테엽", "태엽", e102);
            ps_setup("테옆", "태엽", e102);
            ps_setup("태옆", "태엽", e102);
            ps_setup("스킨쉽", "스킨십", e103);
            ps_setup("멤버쉽", "멤버십", e103);
            ps_setup("리더쉽", "리더십", e103);
            ps_setup("플래그쉽", "플래그십", e103);
            ps_setup("콩글리쉬", "콩글리시", e103);
            ps_setup("재패니쉬", "재패니시", e103);
            ps_setup("페티쉬", "페티시", e103);
            ps_setup("쉴드", "실드", e103);
            ps_setup("쉴더", "실더", e103);
            ps_setup("부쉬", "부시", e103);
            ps_setup("리쉬", "리시", e103);
            ps_setup("대쉬", "대시", e103);
            ps_setup("피쉬", "피시", e103);
            ps_setup("캐쉬", "캐시", e103);
            ps_setup("케쉬", "캐시", e103);
            ps_setup("푸쉬", "푸시", e103);
            ps_setup("쉬핑", "시핑", e103);
            ps_setup("쉽핑", "시핑", e103);
            ps_setup("플랜카드", "플래카드", e104);
            ps_setup("넌센스", "난센스", e105);
            ps_setup("음으로서", "음으로써", e97);
            ps_setup("함으로서", "함으로써", e97);
            ps_setup("됨으로서", "됨으로써", e97);
            ps_setup("봄으로서", "봄으로써", e97);
            ps_setup("짐으로서", "짐으로써", e97);
            ps_setup("쉐도우", "섀도", e106);
            ps_setup("쉐어", "셰어", e106);
            ps_setup("쉐이크", "셰이크", e106);
            ps_setup("쉐이딩", "셰이딩", e106);
            ps_setup("스웩", "스왝", e107);
            ps_setup("스웨그", "스왜그", e107);
            ps_setup("스웨거", "스왜거", e108);
            


            ps2_setup("이예요", "이에요", e2);
            ps2_setup("이예여", "이에여", e2);
            ps2_setup("이예욤", "이에욤", e2);
            ps2_setup("이예염", "이에염", e2);
            ps2_setup("이예용", "이에용", e2);
            ps2_setup("이예영", "이에영", e2);
            ps2_setup("이예욧", "이에욧", e2);
            ps2_setup("이예엿", "이에엿", e2);
            ps2_setup("이예양", "이에양", e2);
            ps2_setup("이예얌", "이에얌", e2);
            ps2_setup("이요", "요", e91);
            ps2_setup("이욤", "욤", e91);
            ps2_setup("이염", "염", e91);
            ps2_setup("이욧", "욧", e91);
            ps2_setup("이얌", "얌", e91);
            ps2_setup("이였", "이었", e92);
            ps2_setup("이엿", "이었", e92);
            ps2_setup("에요", "예요", e2);
            ps2_setup("에여", "예여", e2);
            ps2_setup("에욤", "예욤", e2);
            ps2_setup("에염", "예염", e2);
            ps2_setup("에용", "예용", e2);
            ps2_setup("에영", "예영", e2);
            ps2_setup("에욧", "예욧", e2);
            ps2_setup("에엿", "예엿", e2);
            ps2_setup("에양", "예양", e2);
            ps2_setup("에얌", "예얌", e2);
            ps2_setup("이여도", "이어도", e93);
            ps2_setup("이여서", "이어서", e94);
            ps2_setup("던", "든", e95);
            ps2_setup("바래", "바라", e96);
            ps2_setup("바랬", "바랐", e96);
            ps2_setup("로써", "로서", e97);
            ps2_setup("엄한", "애먼", e98);
            ps2_setup("아니오", "아니요", e99);

            
        }
    }
}
